#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.6f1_a7aea80e3716"
#define UNITY_VERSION_FULL_NICE "2019.4.6f1 (a7aea80e3716)"
#define UNITY_VERSION_BLD 10989224
#define UNITY_VERSION_DATE 1595357385
#define UNITY_VERSION_WIN "2019.4.6.10989224"
#define UNITY_VERSION_BRANCH "2019.4/staging"
